import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Signin from "~/components/Signin";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <Link href={"/dashboard"}>Dashboard</Link>
        <Signin />
      </main>
    </>
  );
};

export default Home;
